### PR TITLE
adds breadcrumb prototype

### PR DESCRIPTION
**Pull request by mandziukGIT**

### CODE REVIEW

**Comment by mandziukGIT** [comment]
It's just prototype, but works fine. Probably it can be done in more elegant way. What is your opinion 🧐

**Comment by Sebosun** [comment]
Talked with Artur and I'll be checking this PR if you don't mind :)

**Comment by Sebosun** [comment]
Personally, I'd suggest not including the Breadcrumbs logic in the main App.vue component, but moving it to each page and let it handle how it displays itself. 

In the Booking section of the page, we will have one other Breadcrumb, that would also have to deal with using applications logic, which could get pretty unreadable if the application scales. 

You could then pass the paths to go back to and displayed breadcrumb title as props and set some default "back" path if prop is not received.

**Comment by mandziukGIT** [comment]
@Sebosun after your suggestions this is what I come up with. Navigation helper component with slots. Chosen public pages implement breadcrumb component into slots with props as you mentioned. Booking section can't really make use of breadcrumbs therefore I suggest to create stepper like component with active prop. wdyt?

**Comment by Sebosun** [comment]
Sounds good, using slots should spare you a lot of overhead in deciding what should be displayed :)

**Pull request merged**
